name: Android CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3️⃣ Set up Android SDK & build tools
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: 34.0.0
          ndk: 25.2.9519653

      # 4️⃣ Grant execute permission to gradlew
      - name: Grant execute permission
        run: chmod +x gradlew

      # 5️⃣ Clean Gradle
      - name: Clean Gradle build
        run: ./gradlew clean

      # 6️⃣ Build APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # 7️⃣ Upload APK artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: JobScoutCanadaApp-debug
          path: app/build/outputs/apk/debug/app-debug.apk
